export const ADMIN_MENUS = [
  { href: "/admin", label: "แดชบอร์ด", icon: "📊" },
  { href: "/admin/website", label: "หน้าแรก (Sections)", icon: "🏠" },
  { href: "/admin/hero", label: "Hero Banner", icon: "🖼️" },
  { href: "/admin/header", label: "เมนู Header", icon: "🧭" },
  { href: "/admin/farms", label: "จัดการฟาร์ม", icon: "🌳" },
  { href: "/admin/orchard", label: "ดูแปลงปลูก", icon: "🛰️" },
  { href: "/admin/plots", label: "แปลงปลูก", icon: "🗺️" },
  { href: "/admin/harvests", label: "เก็บเกี่ยว", icon: "🧺" },
  { href: "/admin/receivings", label: "รับวัตถุดิบ", icon: "🚚" },
  { href: "/admin/quality", label: "คุณภาพ & คัดเกรด", icon: "✅" },
  { href: "/admin/processing", label: "แปรรูป", icon: "⚙️" },
  { href: "/admin/inventory", label: "คลังสินค้า", icon: "📦" },
  { href: "/admin/orders", label: "ขาย & คำสั่งซื้อ", icon: "🧾" },
  { href: "/admin/trace", label: "ตรวจสอบย้อนกลับ", icon: "🔍" },
  { href: "/admin/products", label: "สินค้า (เว็บ)", icon: "🛒" },
  { href: "/admin/customers", label: "ลูกค้า", icon: "👥" },
  { href: "/admin/inquiries", label: "ข้อความติดต่อ", icon: "✉️" },
  { href: "/admin/settings", label: "ตั้งค่า", icon: "⚙️" },
] as const;
